config/routes.rb
Swt::Application.routes.draw do
	
  get "crud_user/index"
  get "crud_user/show"
  get "crud_user/new"
  get "crud_user/create"
  get "crud_user/update"
  get "crud_user/destroy"
	
	resources :users_devices

	resources :user_settings

	resources :positions

	resources :devices

	resources :application_settings

	devise_for :users#, :controllers => {:registration => "registrations"}	
	
	get 'device_by_user' => 'home#device_by_user'
    
	resources :users	
	root :to => 'home#index'	
	
	
	
	
	
	
	

  

end

app/models/application_setting.rb
class ApplicationSetting < ActiveRecord::Base
	self.table_name = 'application_settings'
	self.primary_key = 'id'
end

app/controllers/application_settings_controller.rb
class ApplicationSettingsController < ApplicationController
  before_action :set_application_setting, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
	#load_and_authorize_resource

  # GET /application_settings
  # GET /application_settings.json
  def index
    @application_settings = ApplicationSetting.all
	  respond_to do |format|
		  format.html # show.html.erb
		  format.json { render json: @application_settings.to_json(root: false) }
	  end
  end

  # GET /application_settings/1
  # GET /application_settings/1.json
  def show
  end

  # GET /application_settings/new
  def new
    @application_setting = ApplicationSetting.new
  end

  # GET /application_settings/1/edit
  def edit
  end

  # POST /application_settings
  # POST /application_settings.json
  def create
    @application_setting = ApplicationSetting.new(application_setting_params)

    respond_to do |format|
      if @application_setting.save
        format.html { redirect_to @application_setting, notice: 'Application setting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application_setting }
      else
        format.html { render action: 'new' }
        format.json { render json: @application_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_settings/1
  # PATCH/PUT /application_settings/1.json
  def update
    respond_to do |format|
      if @application_setting.update(application_setting_params)
        format.html { redirect_to @application_setting, notice: 'Application setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_settings/1
  # DELETE /application_settings/1.json
  def destroy
    @application_setting.destroy
    respond_to do |format|
      format.html { redirect_to application_settings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_setting
      @application_setting = ApplicationSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_setting_params
      params[:application_setting]
    end
end

app/helpers/application_settings_helper.rb
module ApplicationSettingsHelper
end

app/views/application_settings/_form.html.erb
<!-- Modal -->
<div class="modal fade" id="applicationSettingModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Global Settings</h4>
			</div>
			<div class="modal-body">
				<%= simple_form_for @application_setting, html: {class: 'form-horizontal' } do |f| %>
				  <% if @application_setting.errors.any? %>
					<div id="error_explanation">
					  <h2><%= pluralize(@application_setting.errors.count, "error") %> prohibited this application_setting from being saved:</h2>
				
					  <ul>
					  <% @application_setting.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					  <% end %>
					  </ul>
					</div>
				  <% end %>
					<%= f.input :registrationEnabled %>
			</div>
			<div class="modal-footer">
				<%= f.submit "submit", :class => 'btn btn-primary' %>
      		</div>
			<% end %>
    	</div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/application_settings/edit.html.erb
<h1>Editing application_setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @application_setting %> |
<%= link_to 'Back', application_settings_path %>

app/views/application_settings/index.html.erb
<h1>Listing application_settings</h1>

<table>
  <thead>
    <tr>
      <th>registrationEnabled</th>
    </tr>
  </thead>

  <tbody>
    <% @application_settings.each do |application_setting| %>
      <tr>
		<td><%= application_setting.registrationEnabled %></td>  
        <td><%= link_to 'Show', application_setting %></td>
        <td><%= link_to 'Edit', edit_application_setting_path(application_setting) %></td>
        <td><%= link_to 'Destroy', application_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application setting', new_application_setting_path %>

app/views/application_settings/new.html.erb
<h1>New application_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', application_settings_path %>

app/views/application_settings/new.js.erb
$('body').append("<%=escape_javascript(render(partial: 'form'))%>")
$('#applicationSettingModal').modal('show')

app/views/application_settings/show.html.erb
<p id="notice"><%= notice %></p>

<%= @application_setting.registrationEnabled %>

<%= link_to 'Edit', edit_application_setting_path(@application_setting) %> |
<%= link_to 'Back', application_settings_path %>