config/routes.rb
Swt::Application.routes.draw do
	
  get "crud_user/index"
  get "crud_user/show"
  get "crud_user/new"
  get "crud_user/create"
  get "crud_user/update"
  get "crud_user/destroy"
	
	resources :users_devices

	resources :user_settings

	resources :positions

	resources :devices

	resources :application_settings

	devise_for :users#, :controllers => {:registration => "registrations"}	
	
	get 'device_by_user' => 'home#device_by_user'
    
	resources :users	
	root :to => 'home#index'	
	
	
	
	
	
	
	

  

end

app/models/position.rb
class Position < ActiveRecord::Base
	has_one :device
	self.table_name = "positions"
	self.primary_key = "id"
	
	# metodo para não deixar o metodo valid do rails ser chamado
	# devido a tabela positions ter um campo | atributo chamado valid
	def self.instance_method_already_implemented?(method_name)
    	return true if method_name == 'valid'
    	return true if method_name == 'valid?'
    	super
	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]
  #load_and_authorize_resource
	before_filter :authenticate_user!

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
	  respond_to do |format|
		  format.html # show.html.erb
		  format.json { render json: @positions.to_json(root: false) }
	  end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
	  @position = Position.find(params[:id])
	  respond_to do |format|
		  format.html # show.html.erb
		  format.json { render json: @position.to_json(root: false) }
	  end
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render action: 'show', status: :created, location: @position }
      else
        format.html { render action: 'new' }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params[:position]
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= simple_form_for @position, html: {class: 'form-horizontal' } do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>
<%=h @position.speed %><br>
<%=h @position.latitude %><br>
<%=h @position.longitude %>
<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>