config/routes.rb
Swt::Application.routes.draw do
	
  get "crud_user/index"
  get "crud_user/show"
  get "crud_user/new"
  get "crud_user/create"
  get "crud_user/update"
  get "crud_user/destroy"
	
	resources :users_devices

	resources :user_settings

	resources :positions

	resources :devices

	resources :application_settings

	devise_for :users#, :controllers => {:registration => "registrations"}	
	
	get 'device_by_user' => 'home#device_by_user'
    
	resources :users	
	root :to => 'home#index'	
	
	
	
	
	
	
	

  

end

app/models/users_device.rb
class UsersDevice < ActiveRecord::Base
	self.table_name = 'users_devices'
	self.primary_key = 'users_id'

	belongs_to :user
	has_many :devices
	#fkp :users_id
	#fkp :devices_id
	
end

app/controllers/users_devices_controller.rb
class UsersDevicesController < ApplicationController
	before_filter :authenticate_user!
  before_action :set_users_device, only: [:show, :edit, :update, :destroy]
  #load_and_authorize_resource

  # GET /users_devices
  # GET /users_devices.json
  def index
    @users_devices = UsersDevice.all
	  respond_to do |format|
		  format.html # show.html.erb
		  format.json { render json: @users_devices.to_json(root: false) }
	  end
  end

  # GET /users_devices/1
  # GET /users_devices/1.json
  def show
  end

  # GET /users_devices/new
  def new
    @users_device = UsersDevice.new
	#render template: 'users_devices/new.js.erb'
  end

  # GET /users_devices/1/edit
  def edit
  end

  # POST /users_devices
  # POST /users_devices.json
  def create
    @users_device = UsersDevice.new(users_device_params)

    respond_to do |format|
      if @users_device.save
        format.html { redirect_to @users_device, notice: 'Users device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @users_device }
      else
        format.html { render action: 'new' }
        format.json { render json: @users_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_devices/1
  # PATCH/PUT /users_devices/1.json
  def update
    respond_to do |format|
      if @users_device.update(users_device_params)
        format.html { redirect_to @users_device, notice: 'Users device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @users_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_devices/1
  # DELETE /users_devices/1.json
  def destroy
    @users_device.destroy
    respond_to do |format|
      format.html { redirect_to users_devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_device
      @users_device = UsersDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_device_params
      params[:users_device]
    end
end

app/helpers/users_devices_helper.rb
module UsersDevicesHelper
end

app/views/users_devices/_form.html.erb
<%= form_for(@users_device) do |f| %>
  <% if @users_device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users_device.errors.count, "error") %> prohibited this users_device from being saved:</h2>

      <ul>
      <% @users_device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_devices/_popup_new.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Modal title</h4>
			</div>
			<div class="modal-body">
				<%= form_for(@users_device) do |f| %>
					<% if @users_device.errors.any? %>
						<div id="error_explanation">
							<h2><%= pluralize(@users_device.errors.count, "error") %> prohibited this users_device from being saved:</h2>
							<ul>
								<% @users_device.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
  					<% end %>
			</div>
			<div class="modal-footer">
				<%= f.submit "submit", :class => 'btn btn-primary' %>
      		</div>
			<% end %>
    	</div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users_devices/edit.html.erb
<h1>Editing users_device</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_device %> |
<%= link_to 'Back', users_devices_path %>

app/views/users_devices/index.html.erb
<h1>Listing users_devices</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users_devices.each do |users_device| %>
      <tr>
        <td><%= link_to 'Show', users_device %></td>
        <td><%= link_to 'Edit', edit_users_device_path(users_device) %></td>
        <td><%= link_to 'Destroy', users_device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Users device', new_users_device_path %>

app/views/users_devices/new.html.erb
<h1>New users_device</h1>

<%= render 'form' %>

<%= link_to 'Back', users_devices_path %>

app/views/users_devices/new.js.erb
$('body').append("<%=escape_javascript(render(partial: 'popup_new'))%>")
$('#myModal').modal('show')

app/views/users_devices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_users_device_path(@users_device) %> |
<%= link_to 'Back', users_devices_path %>