config/routes.rb
Swt::Application.routes.draw do
	
  get "crud_user/index"
  get "crud_user/show"
  get "crud_user/new"
  get "crud_user/create"
  get "crud_user/update"
  get "crud_user/destroy"
	
	resources :users_devices

	resources :user_settings

	resources :positions

	resources :devices

	resources :application_settings

	devise_for :users#, :controllers => {:registration => "registrations"}	
	
	get 'device_by_user' => 'home#device_by_user'
    
	resources :users	
	root :to => 'home#index'	
	
	
	
	
	
	
	

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!
	#load_and_authorize_resource

	def index
        #@last_positions = current_user.last_positions.to_json
        @last_positions = current_user.last_positions
	    respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @last_positions.to_json(root: false) }
        end            
	end
    
    def device_by_user
        index
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/device_by_user.html.erb
<div ng-controller="MapController">
    {{device_by_user.length}}
</div>

app/views/home/index.html.erb
<!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">SWT - Sigma Web Tracker</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">
	    <li class="dropdown">
              	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(:label_my_settings) %><b class="caret"></b></a>
              	<ul class="dropdown-menu">
		  <li><%= link_to t(:label_edit_user_settings), edit_user_registration_path, :remote => true %></li>
              	</ul>
              </li>
              <li class="dropdown">
		<% if user_signed_in? %>
		  <% if current_user.admin? %>
		    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(:label_admin_area) %>
		      <b class="caret"></b>
		    </a>
		    <ul class="dropdown-menu">
		      <li><%= link_to(t(:label_cadastro_users), crud_user_new_path, :remote => true) %></li>
		      <li><%= link_to "Cadastro de Device ", new_device_path, :remote => true %></li>
		    </ul>
		  <% end %>
		<% end %>
	      </li>
              <li><%= link_to t(:label_logout), destroy_session_path(:user), :method => :delete %></li>
	      <li><a href="#"><%= current_user.email %></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
<div id="master_container">
    <section id="map_id">
    </section>
</div>